adapter: 'mysql2'
encoding: 'utf8'
username: <%= ENV['NF_TUMBLEDB_USERNAME'] %>
password: <%= ENV['NF_TUMBLEDB_PASSWORD'] %>
database: <%= ENV['NF_TUMBLEDB_DATABASE'] %>
host: <%= ENV['NF_TUMBLEDB_HOST'] %>

pool: 20
  #weburi: http://localhost:4567
weburi: http://site--rb-tumble--yggqcfg658tn.code.run:4567
secret: 'ihasone'
